name: FlatPreset
main: aieuo\FlatPreset
version: 1.0
api: 3.0.0
load: POSTWORLD
author: aieuo
commands:
 preset:
  description: 好きなブロックでワールド作成
  usage: /preset <pos1 | pos2 | generate>
  permission: op
 
